### ISSUE TITLE
Use Error instance for better integration

### ISSUE THREAD

**Issue by allevo** [aheckmann/node-ses#46]
When amazon returns an error, an [object is used as error](https://github.com/aheckmann/node-ses/blob/master/lib/email.js#L211)

Which is the benefit of this approach ?

**Comment by markstos** [comment]
Are you comparing the current approach returning strings or returning Error objects?

**Comment by allevo** [comment]
I'm concerned about the Object usage instead of Error.
Particularly when the `Error` interface is lost
The used property `Message` is not compliant with the javascript world.
The error handling will be a nightmare.

**Comment by markstos** [comment]
I agree that returning an Error object instead of plain object could be helpful. 

The properties `Type`, `Code` and `Message` were chosen for consistency with the other responses that Amazon provides. 

You are welcome to propose the specifics of an alternate approach. If it's not backwards-compatible, impact on existing code bases using `node-ses` should be considered. 

The official AWS JavaScript SDK and `node-mailer` may be useful references.

**Comment by aheckmann** [comment]
Closing. [This project is no longer maintained](https://github.com/aheckmann/node-ses?tab=readme-ov-file#deprecated).
